<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<OutputType>WinExe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5-preview.*" />
    <PackageReference Include="MonoGame.Runtime.Windows.Vulkan" Version="3.8.5-preview.*" />
    <PackageReference Include="MonoGame.Runtime.Linux.Vulkan" Version="3.8.5-preview.*" />
    <PackageReference Include="MonoGame.Runtime.Mac.Vulkan" Version="3.8.5-preview.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sin3d\Sin3d.csproj" />
  </ItemGroup>
</Project>
