<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.*" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5-preview.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="..\Sin3D\Sin3D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>